language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"
  - "iojs-v1.0.4"
addons:
  code_climate:
    repo_token: d83c767f4b469d90f9cedda8ae1f253e37cee5dd1ef2f92f054c4dc80f8f8999
after_script:
  - cat coverage/lcov.info | codeclimate
